AbcPos.Web/Controllers/ProdajaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AbcPos.Core.Kriterijumi;
using AbcPos.Core.Models;
using AbcPos.Core.Repository;
using AbcPos.Web.ViewModels;

namespace AbcPos.Web.Controllers
{
    public class ProdajaController : Controller
    {
        private Repository m_Repository = new Repository();

        public ActionResult Index(int? idRadnje, DateTime? odDatuma, DateTime? doDatuma)
        {
            var vm = new PregledDokumenataViewModel();
            vm.Kriterijumi.TipDokumenta = TipDokumenta.Prodaja;
            var kriterijum = Session["KriterijumPretrageProdaje"] as KriterijumPretrageDokumenata;
            if (kriterijum == null)
            {
                kriterijum = vm.Kriterijumi;
                Session["KriterijumPretrageProdaje"] = kriterijum;
            }
            else
            {
                vm.Kriterijumi = kriterijum;
            }

            if (odDatuma.HasValue && doDatuma.HasValue)
            {
                vm.Kriterijumi.IdRadnje = idRadnje;
                vm.Kriterijumi.OdDatuma = odDatuma.Value;
                vm.Kriterijumi.DoDatuma = doDatuma.Value;
                vm.PretraziDokumente();
            }
            if (Request.IsAjaxRequest())
            {
                return PartialView("_DokumentiGrid", vm);
            }
            return View("Index", vm);
        }

        public PartialViewResult VratiStavkeRacuna(int idDokumenta)
        {
            var stavke = m_Repository.VratiStavkeDokumenta(idDokumenta);
            return PartialView("_StavkeGrid", stavke);
        }

    }
}

AbcPos.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>

<html>
<head>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="@Url.Content("~/Content/site.css")" />

    <script src="@Url.Content("~/Scripts/jquery-1.6.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/moment.min.js")" type="text/javascript"></script>

    @Html.DevExpress().GetStyleSheets( 
    new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout }, 
    new StyleSheet { ExtensionSuite = ExtensionSuite.Editors }, 
    new StyleSheet { ExtensionSuite = ExtensionSuite.HtmlEditor }, 
    new StyleSheet { ExtensionSuite = ExtensionSuite.GridView }, 
    new StyleSheet { ExtensionSuite = ExtensionSuite.PivotGrid },
    new StyleSheet { ExtensionSuite = ExtensionSuite.Chart },
    new StyleSheet { ExtensionSuite = ExtensionSuite.Report },
	new StyleSheet { ExtensionSuite = ExtensionSuite.Scheduler },
	new StyleSheet { ExtensionSuite = ExtensionSuite.TreeList }
)
    @RenderSection("styles", false)

@Html.DevExpress().GetScripts( 
    new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout }, 
    new Script { ExtensionSuite = ExtensionSuite.HtmlEditor }, 
    new Script { ExtensionSuite = ExtensionSuite.GridView }, 
    new Script { ExtensionSuite = ExtensionSuite.PivotGrid },
    new Script { ExtensionSuite = ExtensionSuite.Editors }, 
    new Script { ExtensionSuite = ExtensionSuite.Chart },
    new Script { ExtensionSuite = ExtensionSuite.Report },
	new Script { ExtensionSuite = ExtensionSuite.Scheduler },
	new Script { ExtensionSuite = ExtensionSuite.TreeList }
)
    @RenderSection("scripts", false)
    <script>
        var app = app || {};
        app.root = '@Url.Content("~/")';
    </script>
</head>
    <body>
        <div id="contentWrapper">
            <header>
                @Html.Partial("_Menu")
            </header>
            @RenderBody()    
        </div>
    </body>
</html>

AbcPos.Web/Views/Shared/_Menu.cshtml
@Html.DevExpress().Menu(
    menu =>
    {
        menu.Name = "mainMenu";
        menu.Items.Add("Artikli", "Artikli").NavigateUrl = @Url.Action("Index", "Artikli");
        menu.Items.Add("Zalihe", "Zalihe").NavigateUrl = @Url.Action("Index", "Zalihe");
        var nabavka = menu.Items.Add("Nabavka", "Nabavka");
        nabavka.Items.Add("Nabavka", "NovaNabavka", "", @Url.Action("NovaNabavka", "Nabavka"));
        nabavka.Items.Add("Pregled nabavke", "PregledNabavke", "", @Url.Action("Index", "Nabavka"));
        menu.Items.Add("Pregled prodaje", "PregledProdaje", "", @Url.Action("Index", "Prodaja"));
    }
).GetHtml()